version: '3.8'
name: ratelimit

services:
  postgresql:
    image: bitnami/postgresql:16.3.0
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    ports:
      - '${POSTGRESQL_PUBLIC_PORT}:5432'
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
    driver: local

